export const NAV_CONTENT_TYPES = Object.freeze({
  NAV_CONTENT_TEXT: 'NAV_CONTENT_TEXT',
  NAV_CONTENT_LINK: 'NAV_CONTENT_LINK',
});

export const PAGE_CONTENT_TYPES = Object.freeze({
  PAGE_CONTENT_TEXT: 'PAGE_CONTENT_TEXT',
  PAGE_CONTENT_LINK_BUTTON: 'PAGE_CONTENT_LINK_BUTTON',
  PAGE_CONTENT_IMAGE: 'PAGE_CONTENT_IMAGE',
  PAGE_CONTENT_CARD: 'PAGE_CONTENT_CARD',
});

export default Object.freeze({
  ...NAV_CONTENT_TYPES,
  ...PAGE_CONTENT_TYPES,
});
